baseURL = 'https://www.imalexblack.dev/'
languageCode = 'en-us'
title= 'Alex Black'
theme = 'typo'
[params]
  # Meta description
  description = "Alex Black's Blog"
  
  # Appearance settings
  theme = 'dark'
  colorPallette = 'catpuccin'


  #Intro on main page, content is markdown
  # homeIntroTitle = 'Hi!'
  # homeIntroContent = "I am a developer"

  # Collection to display on home
  homeCollectionTitle = 'Posts'
  homeCollection = 'posts'

  # Lists parameters
  paginationSize = 100
  listSummaries = false
  listDateFormat = '2 Jan 2006'

  # Breadcrumbs
  breadcrumbs = true

  # Footer
  footerContent = "© 2025 Alex Black"


[[params.menu]]
name = "home"
url =  "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "about"
url = "/about"


[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/alexander-g-black"

[[params.social]]
name = "github"
url = "https://github.com/algabl"

[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/algabl.bsky.social"

[[params.social]]
name = "rss"
url = "/index.xml"

[markup]
[markup.highlight]
style = 'catppuccin-mocha'

[params.umami]
enable = true
websiteId = "1cd9cf5e-0bfe-4d23-a1c2-9159733190bc"
jsLocation = "https://cloud.umami.is/script.js"